FROM {{instance.image_base}}
MAINTAINER {{app.author}}

RUN mkdir -p /app

### install materia (TODO: change when releasing)
# RUN npm install -g materia
RUN mkdir -p /root/.ssh
COPY ./key.pem /root/.ssh/id_rsa
RUN chmod 400 /root/.ssh/id_rsa && ssh -o StrictHostKeyChecking=no git@bumpmann.dtdns.net -p 7777 uptime && git clone ssh://git@bumpmann.dtdns.net:7777/~/materia /app/materia && cd /app/materia && npm install
###

RUN mkdir -p /app/user
COPY . /app/user

{{#if instance.use_runnable}}
WORKDIR /app/user

ENV PATH /app/materia:$PATH
ENV MATERIA_MODE prod

ENTRYPOINT ["/app/user/docker-entrypoint.sh"]

EXPOSE {{instance.port}}
CMD ["materia", "start"]
{{/if}}