FROM {{instance.image_base}}
MAINTAINER {{app.author}}

RUN mkdir -p /app

# invalidate cache
RUN uptime

# RUN npm install -g materia
RUN git clone https://github.com/webshell/materia-server.git /app/materia && cd /app/materia && npm install

RUN mkdir -p /app/user
COPY . /app/user

{{#if instance.use_runnable}}
WORKDIR /app/user

ENV PATH /app/materia:$PATH
ENV MATERIA_MODE prod

ENTRYPOINT ["/app/user/docker-entrypoint.sh"]

EXPOSE {{instance.port}}
CMD ["materia", "start"]
{{/if}}