sudo: true
dist: trusty
language: node_js

node_js:
 - "8.1"

services:
 - postgresql

addons:
  postgresql: "9.4"

before_script:
 - psql -c 'create database materia_test;' -U postgres

env:
  global:
   - POSTGRES_HOST=localhost
   - POSTGRES_PORT=5432
   - POSTGRES_DATABASE=materia_test
   - POSTGRES_USERNAME=postgres
   - POSTGRES_PASSWORD=
  matrix:
   - DIALECT=sqlite
   - DIALECT=postgres

before_install:
 - "npm install -g typescript@2.3.4"
install:
 - "npm install && tsc -p ."
script:
 - "npm test"

branches:
  only:
    - master
    - dev